[package]
name = "adventofcode-2018"
version = "0.1.0"
authors = ["Jacob Mischka <jacob@mischka.me>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
regex = "1.4.2"
lazy_static = "1.4.0"
itertools = "0.9.0"
